### ISSUE TITLE
Same colors isn't collide

### ISSUE THREAD

**Issue by Sigiller** [SlexAxton/css-colorguard#47] opened 2016-06-20 12:28 UTC
No collides with this colors:

```
.foo {
  color: #000000;
  background: #000000;
}
```

But I have collide warning with this:

```
.foo {
  color: #000;
  background: #000000;
}
```

**Comment by ben-eb** [comment] 2016-06-20 12:43
Duplicate of https://github.com/SlexAxton/css-colorguard/issues/30. 😄

**Closed by ben-eb** 2016-06-20 12:43 UTC

**Comment by Sigiller** [comment] 2016-06-20 12:55
Almost, but not. I don't want to suppress this warnings. I expect same behavior with the same colors but there isn't. 

No collides with this colors, for example: 
```
.foo {
  color: black;
  background: black;
}
```

**Comment by ben-eb** [comment] 2016-06-20 13:09
The goal of this module is to warn you about similar colours in your stylesheet, not about insufficient contrast. Depending on the your CSS, this is actually a legitimate use case, for example as a "spoiler warning" class;

```css
.spoiler {
  color: black;
  background: black;
}

.spoiler:hover {
  color: #fff;
}
```

This will black out text from the user until they hover over it.

Maybe this is a good rule to add for [stylelint](http://stylelint.io/) though?

**Comment by Sigiller** [comment] 2016-06-20 13:16
@ben-eb Thanks you for explanation.
